pipeline{
    agent any

    stages{
        stage('build docker image'){
            steps{
                bat 'docker build --no-cache -t vite-app .'
            }
        }
        stage('deploy container'){
            steps{
                bat '''
                docker stop vite-container || exho Container not running
                docker rm vite-container || echo Container not found
                docker run -d -p 8081:80 --name vite-container vite-app
                '''
            }
        }
    }
}